// Package pdf exports AI-generated content (sermons, devotionals, study plans)
// as branded PDF documents using the Logos AI theme.
package pdf

import (
	"fmt"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/go-pdf/fpdf"
)

const (
	// Brand colours (RGB)
	colorNavyR, colorNavyG, colorNavyB     = 15, 23, 42   // dark navy background
	colorGoldR, colorGoldG, colorGoldB     = 212, 175, 55  // gold accent
	colorTextR, colorTextG, colorTextB     = 30, 30, 50    // near-black text
	colorLightR, colorLightG, colorLightB  = 245, 243, 235 // warm cream page
	colorSubR, colorSubG, colorSubB        = 100, 90, 140  // muted purple subtitle
)

// sanitize replaces non-latin1 characters with ASCII equivalents for fpdf.
func sanitize(s string) string {
	var b strings.Builder
	for _, r := range s {
		if r > 0xFF {
			b.WriteRune('?')
		} else {
			b.WriteRune(r)
		}
		_ = utf8.RuneLen(r) // suppress unused import
	}
	return b.String()
}

func newPDF() *fpdf.Fpdf {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(20, 20, 20)
	pdf.SetAutoPageBreak(true, 25)
	return pdf
}

func addHeader(pdf *fpdf.Fpdf, title, subtitle string) {
	// Navy header bar
	pdf.SetFillColor(colorNavyR, colorNavyG, colorNavyB)
	pdf.Rect(0, 0, 210, 38, "F")

	// Gold rule
	pdf.SetDrawColor(colorGoldR, colorGoldG, colorGoldB)
	pdf.SetLineWidth(0.8)
	pdf.Line(0, 38, 210, 38)

	// "LOGOS AI" brand in header
	pdf.SetTextColor(colorGoldR, colorGoldG, colorGoldB)
	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetXY(20, 8)
	pdf.CellFormat(80, 6, "LOGOS AI", "", 0, "L", false, 0, "")

	pdf.SetTextColor(180, 180, 200)
	pdf.SetFont("Helvetica", "", 8)
	pdf.SetXY(20, 15)
	pdf.CellFormat(170, 5, sanitize(time.Now().Format("January 2, 2006")), "", 0, "R", false, 0, "")

	// Title
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont("Helvetica", "B", 18)
	pdf.SetXY(20, 22)
	pdf.MultiCell(170, 7, sanitize(title), "", "L", false)

	// Subtitle (scripture ref / theme)
	if subtitle != "" {
		pdf.SetTextColor(colorGoldR, colorGoldG, colorGoldB)
		pdf.SetFont("Helvetica", "I", 11)
		pdf.SetXY(20, 31)
		pdf.CellFormat(170, 6, sanitize(subtitle), "", 0, "L", false, 0, "")
	}

	// Reset to page body
	pdf.SetXY(20, 45)
	pdf.SetTextColor(colorTextR, colorTextG, colorTextB)
}

func addFooter(pdf *fpdf.Fpdf) {
	pdf.SetFooterFunc(func() {
		pdf.SetY(-15)
		pdf.SetFont("Helvetica", "I", 8)
		pdf.SetTextColor(130, 120, 160)
		pdf.CellFormat(0, 10,
			fmt.Sprintf("Generated by Logos AI  •  Page %d", pdf.PageNo()),
			"", 0, "C", false, 0, "")
		// Gold rule above footer
		pdf.SetDrawColor(colorGoldR, colorGoldG, colorGoldB)
		pdf.SetLineWidth(0.3)
		pdf.Line(20, pdf.GetY()-4, 190, pdf.GetY()-4)
	})
}

func writeBody(pdf *fpdf.Fpdf, text string) {
	pdf.SetFont("Helvetica", "", 11)
	pdf.SetTextColor(colorTextR, colorTextG, colorTextB)
	lineHeight := 6.5

	paragraphs := strings.Split(strings.TrimSpace(text), "\n")
	for _, para := range paragraphs {
		para = strings.TrimSpace(para)
		if para == "" {
			pdf.Ln(lineHeight * 0.5)
			continue
		}
		// Detect headings (all-caps short lines, or lines ending with ":")
		if len(para) < 60 && (strings.ToUpper(para) == para || strings.HasSuffix(para, ":")) {
			pdf.Ln(3)
			pdf.SetFont("Helvetica", "B", 12)
			pdf.SetTextColor(colorNavyR, colorNavyG, colorNavyB)
			pdf.MultiCell(170, 7, sanitize(para), "", "L", false)
			pdf.SetFont("Helvetica", "", 11)
			pdf.SetTextColor(colorTextR, colorTextG, colorTextB)
			continue
		}
		pdf.MultiCell(170, lineHeight, sanitize(para), "", "J", false)
		pdf.Ln(2)
	}
}

// ExportDevotional writes a devotional to a PDF file at outPath.
func ExportDevotional(title, verseRef, theme, content, outPath string) error {
	pdf := newPDF()
	addFooter(pdf)
	pdf.AddPage()
	pdf.SetFillColor(colorLightR, colorLightG, colorLightB)
	pdf.Rect(0, 0, 210, 297, "F")

	sub := verseRef
	if theme != "" {
		sub = verseRef + "  •  " + theme
	}
	addHeader(pdf, title, sub)

	// Gold divider
	pdf.SetDrawColor(colorGoldR, colorGoldG, colorGoldB)
	pdf.SetLineWidth(0.4)
	pdf.Line(20, pdf.GetY(), 190, pdf.GetY())
	pdf.Ln(4)

	writeBody(pdf, content)
	return pdf.OutputFileAndClose(outPath)
}

// ExportSermon writes a sermon to a PDF file at outPath.
func ExportSermon(title, scriptureRef, content, outPath string) error {
	pdf := newPDF()
	addFooter(pdf)
	pdf.AddPage()
	pdf.SetFillColor(colorLightR, colorLightG, colorLightB)
	pdf.Rect(0, 0, 210, 297, "F")

	addHeader(pdf, title, scriptureRef)

	pdf.SetDrawColor(colorGoldR, colorGoldG, colorGoldB)
	pdf.SetLineWidth(0.4)
	pdf.Line(20, pdf.GetY(), 190, pdf.GetY())
	pdf.Ln(4)

	writeBody(pdf, content)
	return pdf.OutputFileAndClose(outPath)
}

// StudyPlanWeek is one week for PDF rendering.
type StudyPlanWeek struct {
	WeekNumber int
	Theme      string
	Reading    string
	Verses     []string
	Notes      string
}

// ExportStudyPlan writes a multi-week study plan to a PDF file at outPath.
func ExportStudyPlan(title, description string, weeks []StudyPlanWeek, outPath string) error {
	pdf := newPDF()
	addFooter(pdf)
	pdf.AddPage()
	pdf.SetFillColor(colorLightR, colorLightG, colorLightB)
	pdf.Rect(0, 0, 210, 297, "F")

	addHeader(pdf, title, description)

	pdf.SetDrawColor(colorGoldR, colorGoldG, colorGoldB)
	pdf.SetLineWidth(0.4)
	pdf.Line(20, pdf.GetY(), 190, pdf.GetY())
	pdf.Ln(6)

	for _, w := range weeks {
		// Week header box
		pdf.SetFillColor(colorNavyR, colorNavyG, colorNavyB)
		pdf.SetTextColor(colorGoldR, colorGoldG, colorGoldB)
		pdf.SetFont("Helvetica", "B", 12)
		pdf.CellFormat(170, 8,
			fmt.Sprintf("  Week %d — %s", w.WeekNumber, sanitize(w.Theme)),
			"", 1, "L", true, 0, "")
		pdf.Ln(2)

		pdf.SetTextColor(colorTextR, colorTextG, colorTextB)
		pdf.SetFont("Helvetica", "B", 10)
		pdf.Cell(30, 6, "Reading:")
		pdf.SetFont("Helvetica", "", 10)
		pdf.MultiCell(140, 6, sanitize(w.Reading), "", "L", false)

		if len(w.Verses) > 0 {
			pdf.SetFont("Helvetica", "B", 10)
			pdf.Cell(30, 6, "Key Verses:")
			pdf.SetFont("Helvetica", "", 10)
			pdf.MultiCell(140, 6, sanitize(strings.Join(w.Verses, " • ")), "", "L", false)
		}

		pdf.SetFont("Helvetica", "B", 10)
		pdf.Cell(0, 6, "Study Notes & Reflection:")
		pdf.Ln(6)
		pdf.SetFont("Helvetica", "", 10)
		pdf.MultiCell(170, 5.5, sanitize(w.Notes), "", "J", false)
		pdf.Ln(6)

		// Light divider
		pdf.SetDrawColor(200, 195, 220)
		pdf.SetLineWidth(0.2)
		pdf.Line(20, pdf.GetY(), 190, pdf.GetY())
		pdf.Ln(4)
	}

	return pdf.OutputFileAndClose(outPath)
}

// ExportNote writes an AI verse note to PDF.
func ExportNote(verseRef, content, outPath string) error {
	pdf := newPDF()
	addFooter(pdf)
	pdf.AddPage()
	pdf.SetFillColor(colorLightR, colorLightG, colorLightB)
	pdf.Rect(0, 0, 210, 297, "F")

	addHeader(pdf, "Study Note", verseRef)
	pdf.Ln(4)
	writeBody(pdf, content)
	return pdf.OutputFileAndClose(outPath)
}
