// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as LogosService from "./logosservice.js";
export {
    LogosService
};

export {
    BibleSummary,
    SpeechSettings,
    VoiceOption
} from "./models.js";
