// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../internal/api/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelImport(): $CancellablePromise<void> {
    return $Call.ByID(1743315666);
}

export function ExportPDF(kind: string, title: string, ref: string, content: string): $CancellablePromise<string> {
    return $Call.ByID(3514457315, kind, title, ref, content);
}

export function GetBibles(language: string): $CancellablePromise<$models.BibleSummary[]> {
    return $Call.ByID(1212372256, language).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetBooks(bibleID: string): $CancellablePromise<api$0.Book[]> {
    return $Call.ByID(272124371, bibleID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetChapter(bibleID: string, chapterID: string): $CancellablePromise<api$0.ChapterContent> {
    return $Call.ByID(1009883520, bibleID, chapterID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetChapters(bibleID: string, bookID: string): $CancellablePromise<api$0.Chapter[]> {
    return $Call.ByID(3038075273, bibleID, bookID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetLibraryAudio returns stored word durations for a library entry if the
 * TTS cache key still matches the current voice/rate; otherwise synthesises
 * fresh and returns new durations.
 */
export function GetLibraryAudio(kind: string, id: number, content: string): $CancellablePromise<$models.SyncedSpeechPlan> {
    return $Call.ByID(295047108, kind, id, content).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetSpeechSettings(): $CancellablePromise<$models.SpeechSettings> {
    return $Call.ByID(915521964).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ImportBibleFile(path: string, name: string, abbr: string, lang: string): $CancellablePromise<void> {
    return $Call.ByID(223262584, path, name, abbr, lang);
}

export function ImportBibleURL(url: string, name: string, abbr: string, lang: string): $CancellablePromise<void> {
    return $Call.ByID(812521391, url, name, abbr, lang);
}

export function IsAIAvailable(): $CancellablePromise<boolean> {
    return $Call.ByID(3001676878);
}

export function IsPaused(): $CancellablePromise<boolean> {
    return $Call.ByID(4051046667);
}

export function IsSpeaking(): $CancellablePromise<boolean> {
    return $Call.ByID(772566807);
}

export function ListAIModels(): $CancellablePromise<string[]> {
    return $Call.ByID(2763716465).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ListLibrary(): $CancellablePromise<$models.LibraryEntry[]> {
    return $Call.ByID(3920274908).then(($result: any) => {
        return $$createType11($result);
    });
}

export function OpenFileDialog(): $CancellablePromise<string> {
    return $Call.ByID(313397803);
}

export function PauseSpeaking(): $CancellablePromise<void> {
    return $Call.ByID(1533575167);
}

/**
 * PrecacheChapter begins synthesising TTS audio for the given chapter HTML/text
 * in the background so that StartChapterPlayback starts instantly.  Safe to call on
 * every chapter navigation — any in-progress precache for a previous chapter is
 * cancelled first.
 */
export function PrecacheChapter(content: string): $CancellablePromise<void> {
    return $Call.ByID(2738297185, content);
}

export function ResumeSpeaking(): $CancellablePromise<void> {
    return $Call.ByID(4217012772);
}

/**
 * SaveLibraryAudio stores TTS cache key + word durations for a library entry
 * so future reads are instant.  Call after SpeakAIContent returns.
 */
export function SaveLibraryAudio(kind: string, id: number, wordDurationsJSON: string): $CancellablePromise<void> {
    return $Call.ByID(852423903, kind, id, wordDurationsJSON);
}

export function SaveToLibrary(kind: string, title: string, ref: string, content: string, model: string): $CancellablePromise<void> {
    return $Call.ByID(257747356, kind, title, ref, content, model);
}

export function Search(bibleID: string, query: string, limit: number): $CancellablePromise<api$0.SearchData> {
    return $Call.ByID(3234682073, bibleID, query, limit).then(($result: any) => {
        return $$createType12($result);
    });
}

export function SetSpeechRate(rate: number): $CancellablePromise<$models.SpeechSettings> {
    return $Call.ByID(1185392639, rate).then(($result: any) => {
        return $$createType8($result);
    });
}

export function SetVoice(voiceID: string): $CancellablePromise<$models.SpeechSettings> {
    return $Call.ByID(2452478551, voiceID).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * SpeakAIContent synthesises and plays the given AI-generated text, returning
 * word durations for live highlighting.  Uses the disk cache so if
 * StartAIPrecache was called first it will begin almost instantly.
 */
export function SpeakAIContent(text: string): $CancellablePromise<$models.SyncedSpeechPlan> {
    return $Call.ByID(1650525108, text).then(($result: any) => {
        return $$createType7($result);
    });
}

export function SpeakChapter(content: string): $CancellablePromise<$models.SyncedSpeechPlan> {
    return $Call.ByID(2517685646, content).then(($result: any) => {
        return $$createType7($result);
    });
}

export function SpeakText(text: string): $CancellablePromise<void> {
    return $Call.ByID(4052024186, text);
}

/**
 * StartAIPrecache begins synthesising TTS audio for the given text in the
 * background and writes it to the disk cache.  Called automatically when AI
 * streaming finishes so that SpeakAIContent is instant for the user.
 */
export function StartAIPrecache(text: string): $CancellablePromise<void> {
    return $Call.ByID(1649298616, text);
}

/**
 * StartAIStream starts an AI generation stream.
 * Events: "ai:token" (string), "ai:done" (empty), "ai:error" (string)
 * action: "explain_verse" | "explain_chapter" | "devotional" | "sermon" | "ask"
 */
export function StartAIStream(action: string, verseRef: string, verseText: string, chapterText: string, bookName: string, chapterNum: string, translation: string, userInput: string): $CancellablePromise<void> {
    return $Call.ByID(1538413697, action, verseRef, verseText, chapterText, bookName, chapterNum, translation, userInput);
}

/**
 * StartChapterPlayback synthesises the entire chapter as one continuous audio
 * stream and plays it with word-level highlight sync.
 * 
 * startWordIndex: pass 0 to start from the beginning; pass a word index to
 * jump (seeks in cached PCM on cache hit, falls back to beginning on miss).
 * 
 * Events emitted:
 *   tts:synthesizing — immediately; frontend should show a spinner.
 *   tts:ready        — {startWordIndex int, wordDurationsMs []int}; audio is
 *                      now playing; frontend should schedule word highlights.
 *   tts:done         — playback cancelled or synthesis failed (frontend cleanup).
 *   tts:error        — synthesis error string (frontend shows the message).
 */
export function StartChapterPlayback(content: string, startWordIndex: number): $CancellablePromise<void> {
    return $Call.ByID(1055706873, content, startWordIndex);
}

export function StopAIStream(): $CancellablePromise<void> {
    return $Call.ByID(4064174223);
}

export function StopSpeaking(): $CancellablePromise<void> {
    return $Call.ByID(4264886695);
}

// Private type creation functions
const $$createType0 = $models.BibleSummary.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = api$0.Book.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = api$0.ChapterContent.createFrom;
const $$createType5 = api$0.Chapter.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.SyncedSpeechPlan.createFrom;
const $$createType8 = $models.SpeechSettings.createFrom;
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = $models.LibraryEntry.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = api$0.SearchData.createFrom;
