// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../internal/api/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetBibles(language: string): $CancellablePromise<$models.BibleSummary[]> {
    return $Call.ByID(1212372256, language).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetBooks(bibleID: string): $CancellablePromise<api$0.Book[]> {
    return $Call.ByID(272124371, bibleID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetChapter(bibleID: string, chapterID: string): $CancellablePromise<api$0.ChapterContent> {
    return $Call.ByID(1009883520, bibleID, chapterID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetChapters(bibleID: string, bookID: string): $CancellablePromise<api$0.Chapter[]> {
    return $Call.ByID(3038075273, bibleID, bookID).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetSpeechSettings(): $CancellablePromise<$models.SpeechSettings> {
    return $Call.ByID(915521964).then(($result: any) => {
        return $$createType7($result);
    });
}

export function IsSpeaking(): $CancellablePromise<boolean> {
    return $Call.ByID(772566807);
}

export function Search(bibleID: string, query: string, limit: number): $CancellablePromise<api$0.SearchData> {
    return $Call.ByID(3234682073, bibleID, query, limit).then(($result: any) => {
        return $$createType8($result);
    });
}

export function SetSpeechRate(rate: number): $CancellablePromise<$models.SpeechSettings> {
    return $Call.ByID(1185392639, rate).then(($result: any) => {
        return $$createType7($result);
    });
}

export function SetVoice(voiceID: string): $CancellablePromise<$models.SpeechSettings> {
    return $Call.ByID(2452478551, voiceID).then(($result: any) => {
        return $$createType7($result);
    });
}

export function SpeakText(text: string): $CancellablePromise<void> {
    return $Call.ByID(4052024186, text);
}

export function StopSpeaking(): $CancellablePromise<void> {
    return $Call.ByID(4264886695);
}

// Private type creation functions
const $$createType0 = $models.BibleSummary.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = api$0.Book.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = api$0.ChapterContent.createFrom;
const $$createType5 = api$0.Chapter.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.SpeechSettings.createFrom;
const $$createType8 = api$0.SearchData.createFrom;
