// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../internal/api/models.js";

export class BibleSummary {
    "id": string;
    "abbreviation": string;
    "name": string;
    "nameLocal": string;
    "description": string;
    "language": api$0.Language;
    "type": string;
    "source": string;

    /** Creates a new BibleSummary instance. */
    constructor($$source: Partial<BibleSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("abbreviation" in $$source)) {
            this["abbreviation"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("nameLocal" in $$source)) {
            this["nameLocal"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = (new api$0.Language());
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BibleSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): BibleSummary {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("language" in $$parsedSource) {
            $$parsedSource["language"] = $$createField5_0($$parsedSource["language"]);
        }
        return new BibleSummary($$parsedSource as Partial<BibleSummary>);
    }
}

export class SpeechSettings {
    "available": boolean;
    "engine": string;
    "rate": number;
    "activeVoice"?: VoiceOption | null;
    "voices": VoiceOption[];

    /** Creates a new SpeechSettings instance. */
    constructor($$source: Partial<SpeechSettings> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("engine" in $$source)) {
            this["engine"] = "";
        }
        if (!("rate" in $$source)) {
            this["rate"] = 0;
        }
        if (!("voices" in $$source)) {
            this["voices"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SpeechSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): SpeechSettings {
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("activeVoice" in $$parsedSource) {
            $$parsedSource["activeVoice"] = $$createField3_0($$parsedSource["activeVoice"]);
        }
        if ("voices" in $$parsedSource) {
            $$parsedSource["voices"] = $$createField4_0($$parsedSource["voices"]);
        }
        return new SpeechSettings($$parsedSource as Partial<SpeechSettings>);
    }
}

export class VoiceOption {
    "name": string;
    "id": string;
    "engine": string;
    "label": string;

    /** Creates a new VoiceOption instance. */
    constructor($$source: Partial<VoiceOption> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("engine" in $$source)) {
            this["engine"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VoiceOption instance from a string or object.
     */
    static createFrom($$source: any = {}): VoiceOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VoiceOption($$parsedSource as Partial<VoiceOption>);
    }
}

// Private type creation functions
const $$createType0 = api$0.Language.createFrom;
const $$createType1 = VoiceOption.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($$createType1);
