// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Book {
    "id": string;
    "bibleId": string;
    "abbreviation": string;
    "name": string;
    "nameLong": string;

    /** Creates a new Book instance. */
    constructor($$source: Partial<Book> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("bibleId" in $$source)) {
            this["bibleId"] = "";
        }
        if (!("abbreviation" in $$source)) {
            this["abbreviation"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("nameLong" in $$source)) {
            this["nameLong"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Book instance from a string or object.
     */
    static createFrom($$source: any = {}): Book {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Book($$parsedSource as Partial<Book>);
    }
}

export class Chapter {
    "id": string;
    "bibleId": string;
    "bookId": string;
    "number": string;
    "position": number;

    /** Creates a new Chapter instance. */
    constructor($$source: Partial<Chapter> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("bibleId" in $$source)) {
            this["bibleId"] = "";
        }
        if (!("bookId" in $$source)) {
            this["bookId"] = "";
        }
        if (!("number" in $$source)) {
            this["number"] = "";
        }
        if (!("position" in $$source)) {
            this["position"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Chapter instance from a string or object.
     */
    static createFrom($$source: any = {}): Chapter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Chapter($$parsedSource as Partial<Chapter>);
    }
}

export class ChapterContent {
    "id": string;
    "bibleId": string;
    "bookId": string;
    "number": string;
    "reference": string;
    "content": string;
    "verseCount": number;
    "copyright": string;
    "next": ChapterRef | null;
    "previous": ChapterRef | null;

    /** Creates a new ChapterContent instance. */
    constructor($$source: Partial<ChapterContent> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("bibleId" in $$source)) {
            this["bibleId"] = "";
        }
        if (!("bookId" in $$source)) {
            this["bookId"] = "";
        }
        if (!("number" in $$source)) {
            this["number"] = "";
        }
        if (!("reference" in $$source)) {
            this["reference"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("verseCount" in $$source)) {
            this["verseCount"] = 0;
        }
        if (!("copyright" in $$source)) {
            this["copyright"] = "";
        }
        if (!("next" in $$source)) {
            this["next"] = null;
        }
        if (!("previous" in $$source)) {
            this["previous"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChapterContent instance from a string or object.
     */
    static createFrom($$source: any = {}): ChapterContent {
        const $$createField8_0 = $$createType1;
        const $$createField9_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("next" in $$parsedSource) {
            $$parsedSource["next"] = $$createField8_0($$parsedSource["next"]);
        }
        if ("previous" in $$parsedSource) {
            $$parsedSource["previous"] = $$createField9_0($$parsedSource["previous"]);
        }
        return new ChapterContent($$parsedSource as Partial<ChapterContent>);
    }
}

export class ChapterRef {
    "id": string;
    "number": string;
    "bookId": string;

    /** Creates a new ChapterRef instance. */
    constructor($$source: Partial<ChapterRef> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("number" in $$source)) {
            this["number"] = "";
        }
        if (!("bookId" in $$source)) {
            this["bookId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChapterRef instance from a string or object.
     */
    static createFrom($$source: any = {}): ChapterRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChapterRef($$parsedSource as Partial<ChapterRef>);
    }
}

export class Language {
    "id": string;
    "name": string;
    "nameLocal": string;
    "script": string;
    "scriptDirection": string;

    /** Creates a new Language instance. */
    constructor($$source: Partial<Language> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("nameLocal" in $$source)) {
            this["nameLocal"] = "";
        }
        if (!("script" in $$source)) {
            this["script"] = "";
        }
        if (!("scriptDirection" in $$source)) {
            this["scriptDirection"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Language instance from a string or object.
     */
    static createFrom($$source: any = {}): Language {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Language($$parsedSource as Partial<Language>);
    }
}

export class SearchData {
    "query": string;
    "limit": number;
    "offset": number;
    "total": number;
    "verseCount": number;
    "verses": SearchVerse[];

    /** Creates a new SearchData instance. */
    constructor($$source: Partial<SearchData> = {}) {
        if (!("query" in $$source)) {
            this["query"] = "";
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("verseCount" in $$source)) {
            this["verseCount"] = 0;
        }
        if (!("verses" in $$source)) {
            this["verses"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchData instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchData {
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("verses" in $$parsedSource) {
            $$parsedSource["verses"] = $$createField5_0($$parsedSource["verses"]);
        }
        return new SearchData($$parsedSource as Partial<SearchData>);
    }
}

export class SearchVerse {
    "id": string;
    "orgId": string;
    "bookId": string;
    "bibleId": string;
    "chapterId": string;
    "reference": string;
    "text": string;

    /** Creates a new SearchVerse instance. */
    constructor($$source: Partial<SearchVerse> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("orgId" in $$source)) {
            this["orgId"] = "";
        }
        if (!("bookId" in $$source)) {
            this["bookId"] = "";
        }
        if (!("bibleId" in $$source)) {
            this["bibleId"] = "";
        }
        if (!("chapterId" in $$source)) {
            this["chapterId"] = "";
        }
        if (!("reference" in $$source)) {
            this["reference"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchVerse instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchVerse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchVerse($$parsedSource as Partial<SearchVerse>);
    }
}

// Private type creation functions
const $$createType0 = ChapterRef.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = SearchVerse.createFrom;
const $$createType3 = $Create.Array($$createType2);
