// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBibles(arg1) {
  return window['go']['main']['App']['GetBibles'](arg1);
}

export function GetBooks(arg1) {
  return window['go']['main']['App']['GetBooks'](arg1);
}

export function GetChapter(arg1, arg2) {
  return window['go']['main']['App']['GetChapter'](arg1, arg2);
}

export function GetChapters(arg1, arg2) {
  return window['go']['main']['App']['GetChapters'](arg1, arg2);
}

export function GetTTSEngine() {
  return window['go']['main']['App']['GetTTSEngine']();
}

export function GetVerse(arg1, arg2) {
  return window['go']['main']['App']['GetVerse'](arg1, arg2);
}

export function IsSpeaking() {
  return window['go']['main']['App']['IsSpeaking']();
}

export function Search(arg1, arg2, arg3) {
  return window['go']['main']['App']['Search'](arg1, arg2, arg3);
}

export function SpeakText(arg1) {
  return window['go']['main']['App']['SpeakText'](arg1);
}

export function StopSpeaking() {
  return window['go']['main']['App']['StopSpeaking']();
}
