// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tts} from '../models';
import {api} from '../models';
import {main} from '../models';

export function CancelImport():Promise<void>;

export function ExportPDF(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetActiveVoice():Promise<tts.VoiceEntry>;

export function GetBibles(arg1:string):Promise<Array<api.Bible>>;

export function GetBooks(arg1:string):Promise<Array<api.Book>>;

export function GetChapter(arg1:string,arg2:string):Promise<api.ChapterContent>;

export function GetChapters(arg1:string,arg2:string):Promise<Array<api.Chapter>>;

export function GetTTSEngine():Promise<string>;

export function GetTTSRate():Promise<number>;

export function GetVerse(arg1:string,arg2:string):Promise<api.VerseContent>;

export function ImportBibleFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ImportBibleURL(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function IsAIAvailable():Promise<boolean>;

export function IsPaused():Promise<boolean>;

export function IsSpeaking():Promise<boolean>;

export function ListAIModels():Promise<Array<string>>;

export function ListLibrary():Promise<Array<main.LibraryEntry>>;

export function ListVoices():Promise<Array<tts.VoiceEntry>>;

export function OpenFileDialog():Promise<string>;

export function PauseSpeaking():Promise<void>;

export function ResumeSpeaking():Promise<void>;

export function SaveToLibrary(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function Search(arg1:string,arg2:string,arg3:number):Promise<api.SearchData>;

export function SetTTSRate(arg1:number):Promise<void>;

export function SetVoice(arg1:string):Promise<void>;

export function SpeakSynced(arg1:string):Promise<Array<number>>;

export function SpeakText(arg1:string):Promise<void>;

export function StartAIStream(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<void>;

export function StopAIStream():Promise<void>;

export function StopSpeaking():Promise<void>;
