// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function GetBibles(arg1:string):Promise<Array<api.Bible>>;

export function GetBooks(arg1:string):Promise<Array<api.Book>>;

export function GetChapter(arg1:string,arg2:string):Promise<api.ChapterContent>;

export function GetChapters(arg1:string,arg2:string):Promise<Array<api.Chapter>>;

export function GetTTSEngine():Promise<string>;

export function GetVerse(arg1:string,arg2:string):Promise<api.VerseContent>;

export function IsSpeaking():Promise<boolean>;

export function Search(arg1:string,arg2:string,arg3:number):Promise<api.SearchData>;

export function SpeakText(arg1:string):Promise<void>;

export function StopSpeaking():Promise<void>;
